### PR TITLE
Migrate to spotify/web-scripts #160

### PR DESCRIPTION
**Pull request by arjbholu**

### CODE REVIEW

**Comment by krissalvador27** [comment]
Hey @arjbholu, looking deeper into this there are a few things we might need to add/change.

1. The `@spotify/eslint-config-react` also uses the eslint-plugin-jsx-a11y so we'll need to add that library as well. Opened a [PR](https://github.com/spotify/web-scripts/pull/42) to fix that documentation 😅.
2. Eslint will most likely complain about our jest tests so we'll need to add `eslint-plugin-jest` as a devDependency and include that as a plugin in the `eslintrc.json` like so `plugins: ["jest"]`.
3. We need to create a `prettier.config.js` file and extend it with spotify's prettier config, documented [here](https://github.com/spotify/web-scripts/tree/master/packages/prettier-config#usage).
4. Then in our `eslintrc.json` we add "prettier" as the last item extends
```
  "extends": [
    "@spotify/eslint-config-base",
    "@spotify/eslint-config-react",
    "prettier"
  ]
```

The test should still fail because we'll have some straight forward linting errors that need fixing as well as some jsx-a11y errors. Will definitely help you out once we get to that step since it will most likely be a lot of errors that touch a lot of the files. 😅

**Comment by krissalvador27** [comment]
Hey @arjbholu, just following up on this? Need any help?

**Comment by arjbholu** [comment]
@krissalvador27 I will work on this.
Will let you know if any help is required. 
Thanks

**Comment by krissalvador27** [comment]
Closing in favor of #172

**Pull request closed without merging**
