### PR TITLE
Decorate XYPlot onMouseEnter and onMouseLeave events

### LINKED ISSUE #176: Decorate XYPlot onMouseEnter and onMouseLeave events
We decorate `onMouseMove`, `onMouseDown`, `onMouseUp`, `onClick` with helpful information like xScale, yScale, xValue and yValue. We should decorate `onMouseEnter` and `onMouseLeave` for consistency.

### PR DESCRIPTION
**Pull request by tanayv**
- Created a binding declaration for the onMouseEnter and onMouseLeave events similar to the onClick, onMouseDown etc. events for XYPlot
- Removed original declaration of onMouseEnter and onMouseLeave events
- Closes #176

### CODE REVIEW

**Comment by krissalvador27** [comment]
Hey @tanayv, sorry for the delay! This looks good! Do you have bandwidth to also update the event handler test in `XYPlot.spec.js`?

**Comment by tanayv** [comment]
Hi @krissalvador27,

I can take that up too! (Hopefully, my taking it up requires less work on your part than actually doing it yourself)

Just need a quick clarification: In `XYPlot.spec.js`, do you just need me to uncomment the tests related to `onMouseLeave` and `onMouseEnter`, or are there more specialized tests that I can write to detect if the events are being decorated as required? 

Thanks!

**Comment by krissalvador27** [comment]
@tanayv Yes, it would be a big help! 

Yeah, I think we need to do some clean up on `XYPlot.spec.js`. The commented out event handlers are all valid and should be tested to make sure they are called with the arguments we expect.

**Comment by tanayv** [comment]
Hey @krissalvador27, 

So I uncommented the tests and there were a bunch of tests in components that are using the XYPlot, mostly along the lines:
`Warning: Received NaN for the `y` attribute. If this is expected, cast the value to a string.` 

I did some digging around but I think I'll need a bit of help, and unfortunately, I don't see myself having the bandwidth to do it in the coming week or so. So yes, feel free to take it up on your side!

**Comment by krissalvador27** [comment]
Thanks @tanayv! Will merge this in and update the tests separately.

**Pull request merged**
