### PR TITLE
Added Precommit hooks

### LINKED ISSUE #175: Add precommit hooks from spotify web-scripts
We've migrated our eslint and prettier configs to pull from Spotify's.
I don't think we necessarily need to add all the scripts they're using but we should take advantage of `husky` precommit hooks.

```
{
  "scripts": {
    "test": "web-scripts test",
    "lint": "web-scripts lint",
    "build": "web-scripts build",
    "commit": "web-scripts commit",
    "release": "web-scripts release"
  },
  "husky": {
    "hooks": {
      "commit-msg": "web-scripts commitmsg",
      "pre-commit": "web-scripts precommit"
    }
  }
}
```

See here for more documentation https://github.com/spotify/web-scripts

### PR DESCRIPTION
**Pull request by Patil2099**
Fixes #175

### CODE REVIEW

**Comment by krissalvador27** [comment]
@Patil2099 There are some conflicts and the build is failing. Can you fix those and I can take a look after?

**Comment by krissalvador27** [comment]
Hey @Patil2099, just following up on this. Let me know if you need any support!

**Comment by Patil2099** [comment]
Should I make a new pr ? @krissalvador27

**Comment by Patil2099** [comment]
@krissalvador27 Can you help me in resolving this conflict?

**Comment by krissalvador27** [comment]
@Patil2099 feel free to pull in master and use the latest package.json and then make the husky updates

**Comment by krissalvador27** [comment]
Closing in favor of https://github.com/spotify/reactochart/pull/191

**Pull request closed without merging**
